{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "import tkinter.font as tkFont\n",
    "class A:\n",
    "    def __init__(self, master=None):\n",
    "        self.root = master\n",
    "        self.root.geometry('800x600+200+200')\n",
    "        self.root.title('HealthCare APP')\n",
    "        self.root.configure(bg='silver')\n",
    "        \n",
    "        self.frm1 = Frame(self.root, bg='skyblue')\n",
    "        self.frm2 = Frame(self.root)\n",
    "        self.frm3 = Frame(self.root, bg='tan')\n",
    "        self.createpage()\n",
    "    def call_back(self, event):\n",
    "        print('现在的位置是：', event.x_root, event.y_root)\n",
    "    \n",
    "    def createpage(self):\n",
    "        word1 = tkFont.Font(family='Arial', size=15, weight=tkFont.BOLD)\n",
    "        word2 = tkFont.Font(family='Cambria', size=15, weight=tkFont.BOLD)\n",
    "        word3 = tkFont.Font(family='Helvetica', size=20, weight=tkFont.BOLD)\n",
    "        def gym1():\n",
    "            result1.configure(text='地址:內蒙古100號')\n",
    "            result2.configure(text='費用:200')\n",
    "            result3.configure(text='營業時間:0:00-24:00')\n",
    "            result4.configure(text='人數:1000')\n",
    "        \n",
    "        def gym2():\n",
    "            result1.configure(text='地址:台北市信義區200號')\n",
    "            result2.configure(text='費用:100')\n",
    "            result3.configure(text='營業時間:9:00-23:00')\n",
    "            result4.configure(text='人數:500')\n",
    "            \n",
    "        def gym3():\n",
    "            result1.configure(text='地址:新竹市9487號')\n",
    "            result2.configure(text='費用:1000')\n",
    "            result3.configure(text='營業時間:12:00-21:00')\n",
    "            result4.configure(text='人數:100')\n",
    "            \n",
    "        def gym():\n",
    "            list_button1.configure(text='管長成吉思汗', command=gym1)\n",
    "            list_button2.configure(text='世界健身房', command=gym2)\n",
    "            list_button3.configure(text='四健客', command=gym3)\n",
    "            \n",
    "        def eat1():\n",
    "            result1.configure(text='電話:0123456789')\n",
    "            result2.configure(text='菜單:熟成牛排')\n",
    "            result3.configure(text='卡路里:1234kcal')\n",
    "            result4.configure(text='評價:10顆星')\n",
    "        \n",
    "        def eat2():\n",
    "            result1.configure(text='電話:0987654321')\n",
    "            result2.configure(text='菜單:頂級雞胸肉')\n",
    "            result3.configure(text='卡路里:400kcal')\n",
    "            result4.configure(text='評價:9顆星')\n",
    "            \n",
    "        def eat3():\n",
    "            result1.configure(text='電話:新竹市9487號')\n",
    "            result2.configure(text='菜單:黃金高蛋白')\n",
    "            result3.configure(text='卡路里:105kcal')\n",
    "            result4.configure(text='評價:8顆星')\n",
    "            \n",
    "        def eat():\n",
    "            list_button1.configure(text='好好吃', command=eat1)\n",
    "            list_button2.configure(text='營養滿分餐盒', command=eat2)\n",
    "            list_button3.configure(text='健客必需補給', command=eat3)\n",
    "            \n",
    "        def speech1():\n",
    "            result1.configure(text='講者:台大林壽商教授')\n",
    "            result2.configure(text='地點:台大大講堂')\n",
    "            result3.configure(text='時間:12/31 16:00-18:00')\n",
    "            result4.configure(text='報名網址:http.ntu112')\n",
    "        \n",
    "        def speech2():\n",
    "            result1.configure(text='講者:陸棲巴護理師')\n",
    "            result2.configure(text='地點:101大樓會議室')\n",
    "            result3.configure(text='時間:11/15 13:00-16:00')\n",
    "            result4.configure(text='報名網址:http.101')\n",
    "            \n",
    "        def speech3():\n",
    "            result1.configure(text='講者:高復率醫生')\n",
    "            result2.configure(text='地點:北一女中教學館')\n",
    "            result3.configure(text='時間:2/14 10:00-11:30')\n",
    "            result4.configure(text='報名網址:http.handsome')\n",
    "            \n",
    "        def speech():\n",
    "            list_button1.configure(text='活力四射', command=speech1)\n",
    "            list_button2.configure(text='每朝健康', command=speech2)\n",
    "            list_button3.configure(text='運動新世界', command=speech3)\n",
    "        \n",
    "        def PE1():\n",
    "            result1.configure(text='活動:爬山健走')\n",
    "            result2.configure(text='時間:12/6(日)晚上6點')\n",
    "            result3.configure(text='地點:象山')\n",
    "            result4.configure(text='參加獎品:運動水壺一個')\n",
    "        \n",
    "        def PE2():\n",
    "            result1.configure(text='活動:游泳')\n",
    "            result2.configure(text='時間:日月潭')\n",
    "            result3.configure(text='地點:11/11(三)中午11點')\n",
    "            result4.configure(text='參加獎品:毛巾一條')\n",
    "            \n",
    "        def PE3():\n",
    "            result1.configure(text='活動:有氧運動')\n",
    "            result2.configure(text='時間:11/23(一)早上5點')\n",
    "            result3.configure(text='地點:大安森林公園')\n",
    "            result4.configure(text='參加獎品:T-shirt一件')\n",
    "            \n",
    "        def PE():\n",
    "            list_button1.configure(text='登峰造極', command=PE1)\n",
    "            list_button2.configure(text='四海游龍', command=PE2)\n",
    "            list_button3.configure(text='公園土風舞', command=PE3)\n",
    "        \n",
    "        \n",
    "        result1 = Label(self.frm1, bg='skyblue')\n",
    "        result1.place(x=150,y=100)\n",
    "        result2 = Label(self.frm1, bg='skyblue')\n",
    "        result2.place(x=150,y=150)\n",
    "        result3 = Label(self.frm1, bg='skyblue')\n",
    "        result3.place(x=150,y=200)\n",
    "        result4 = Label(self.frm1, bg='skyblue')\n",
    "        result4.place(x=150,y=250)\n",
    "        \n",
    "        \n",
    "        list_button1 = Button(self.frm1)\n",
    "        list_button1.place(x=0,y=100)\n",
    "        list_button2 = Button(self.frm1)\n",
    "        list_button2.place(x=0,y=150)\n",
    "        list_button3 = Button(self.frm1)\n",
    "        list_button3.place(x=0,y=200)\n",
    "        \n",
    "        menu = Menu(self.root)\n",
    "        self.root.config(menu=menu)\n",
    "        filemenu = Menu(menu)\n",
    "        \n",
    "        self.frm1.config(height=600, width=800)\n",
    "        Label(self.frm1, text='搜尋結果', bg='lawngreen', font=word1).place(in_=self.frm1,x=150,y=10)\n",
    "        self.frm1.place(x=170, y=50)\n",
    "        self.frm2.config(bg='yellow', height=250, width=150)\n",
    "        Label(self.frm2, text='搜尋項目', bg='orchid', font=word2).place(x=20,y=10)\n",
    "        self.frm2.place(x=10, y=50)\n",
    "        self.frm3.config(height=40, width=150)\n",
    "        Label(self.frm3, text='用戶名稱:OOO', bg='tan', font=word3).place(in_=self.frm3, anchor=NW)\n",
    "        self.frm3.place(x=10, y=5)\n",
    "\n",
    "        Button(self.frm2, text='健身房', command=gym).place(x=20, y=50, width=100)\n",
    "        Button(self.frm2, text='餐廳', command=eat).place(x=20, y=100, width=100)\n",
    "        Button(self.frm2, text='健康講座', command=speech).place(x=20, y=150, width=100)\n",
    "        Button(self.frm2, text='體育活動', command=PE).place(x=20, y=200, width=100)\n",
    "    \n",
    "if __name__ == '__main__':\n",
    "    root = Tk()\n",
    "    A(root)\n",
    "    mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
